version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    command: --check-caps false
    restart: always
    ports: 
      - 51663:1972
      - 52663:52773
      - 53773
    volumes:
 #     - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app
